# fly.toml app configuration file generated for nufogy-api on 2023-10-01T16:11:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nufogy-api"
primary_region = "dfw"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
