# Generated by Django 4.2.5 on 2023-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExcersiceRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='peso_usado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='repeticiones_hechas',
            field=models.IntegerField(default=0),
        ),
    ]
