# Generated by Django 4.2.5 on 2023-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExcersiceRegister', '0002_registrodiario_peso_usado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='ultima_serie',
            field=models.IntegerField(default=0),
        ),
    ]
