# Generated by Django 4.2.5 on 2023-09-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyExcersiceRegister', '0003_registrodiario_ultima_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodiario',
            name='ultima_serie',
        ),
    ]
