# Generated by Django 4.2.5 on 2023-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(default='4 Series 12 Repeticiones 20 Kilos'),
        ),
    ]
