# Generated by Django 4.2.5 on 2023-09-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_alter_ejercicio_id_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('alimentos', models.ManyToManyField(related_name='comidas', to='nutrition.alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('comidas', models.ManyToManyField(related_name='dietas', to='nutrition.comida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
    ]
