# Generated by Django 4.2.5 on 2023-09-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nufobot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
