# Generated by Django 4.2.5 on 2023-09-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nufobot', '0004_mensaje_respuesta_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='respuesta',
        ),
    ]
