# Generated by Django 4.2.5 on 2023-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nufobot', '0005_remove_mensaje_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='ai_role',
            field=models.BooleanField(default=False),
        ),
    ]
