# Generated by Django 4.2.5 on 2023-10-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_ejercicio_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='isTrainer',
            field=models.BooleanField(default=False),
        ),
    ]
